import "./globals.css";

import { FxThemeController } from "@/components/FxUI/AppShell/FxThemeController";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FxThemeController />
        {children}
      </body>
    </html>
  );
}
